partner: &common
  environment:
    sleep: 0
    actions:
      timeout: 60
  endpoints:
    endpoint1: 
      url: "/"
      inputType: xml
      wsdl: wsdl_1
    endpointn:
      url: "/GestorConexionesEnLinea/Enlace"
      inputType: xml
      wsdl: wsdl_1
    endpoint2:
      url: "/url_param"
      inputType: url
      methodId: method
    endpoint3:
      url: "/json"
      inputType: json
      methodId: method
  methods: &methods
      login: &methodlogin
        dependence: &logindependence
          methods:
        params: &loginparams
          sessionid:
          initiator:
          pin:
      procesar: &methodprocesar
        serviceId: NomEmpresa
        dependence: &procesardependence
          methods:
            query:
        params: &procesarparams
          operacion:
          parametros:
            ModBusqueda:
            parametroExclusivo1:
            NumMaxSaldos:
            Aviso:
            NomEmpresa:
            NumServicio:
            IdentificadorS1:
      query:
        params:
          operacion:
          account:
  services: &services
    enee: &enee
      methods: &eneemethods
        <<: *methods
    aguas: &aguas
      methods: &aguasmethods
        <<: *methods
    sanaa: &sanaa
      methods: &sanaamethods
        <<: *methods