partner: &common
  validationes: &validationes
    fields: &fields
      account: account
      amount: amount
    rules: &rules
      accountrules: &accountrules
        rule1: account >0
      amountrules: &amountrules
        rule1: amount >0
  methods: &methods
    login: &login
      fields: &loginfields
        sessionid:
        initiator:
        pin:
      rules: &loginrules
        rule1: initiator.length >0
        rule2: pin.length > 0
        rule3: sessionid.length  > 0
    procesar: &query
      fields: &procesarfields
        operacion:
        NomEmpresa:
        ModBusqueda:
      rules: &procesarrules
        rule1: operacion == 'ConNor'
        rule2: NomEmpresa.length > 1
        rule3: ModBusqueda == 20
    query:
      fields:
        account:
      rules:
        rule1: account > 0
  services: &services
    enee: &enee
      methods: &eneemethods
        <<: *methods
    aguas: &aguas
      methods: &aguasmethods
        <<: *methods